repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.253
    hooks:
    - id: ruff
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
-   repo: local
    hooks:
    -   id: export-requirements
        name: Export requirements.txt
        language: system
        pass_filenames: false
        entry: poetry export -o requirements.txt
        files: ^(pyproject.toml|poetry.lock)$