

name: Test and Publish

on:
  pull_request:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ '3.9', '3.10', '3.11' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ matrix.python_version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Poetry Install
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      env:
        POETRY_HTTP_BASIC_NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        POETRY_HTTP_BASIC_NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        poetry config virtualenvs.in-project true
        poetry install
    - name: Type Checking
      run: |
        poetry run mypy
    - name: Test
      run: |
        poetry run pytest


# UNCOMMENT TO USE THIS ACTION WORKFLOW AND PUBLISH TO NEXUS
# EXCLUDED IN TEMPLATE AS WE DONT NEED THE TEMPLATE AS A PACKAGE

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.8'
  #   - name: Install Poetry
  #     run: |
  #       pip install poetry
  #   - name: Snapshot Version
  #     if: ${{ github.ref_type == 'branch' }}
  #     run: |
  #       VERSION=$(poetry version --short)
  #       poetry version "${VERSION}.dev0+$(git rev-parse --short "$GITHUB_SHA")"
  #   - name: Build and Publish Release
  #     env:
  #       POETRY_HTTP_BASIC_NEXUS_UPLOAD_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  #       POETRY_HTTP_BASIC_NEXUS_UPLOAD_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  #     run: |
  #       poetry config repositories.nexus-upload https://nexus.snap40.com/repository/pypi/
  #       poetry publish --build --repository="nexus-upload"
